apiVersion: v1
kind: Pod
metadata:
  name: redis-client
  namespace: redis-lab
  labels:
    app.kubernetes.io/name: redis-client
spec:
  restartPolicy: Never
  containers:
    - name: redis-client
      image: redis:7.2-alpine
      command:
        - sleep
        - "86400"
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 256Mi

